type = "checkout_ui_extension"
name = "delivery-date"

extension_points = [
  'Checkout::Dynamic::Render'
]

[capabilities]
api_access = true

[[metafields]]
 namespace = "detail"
 key = "date"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
# [settings]
#   [[settings.fields]]
#   key = "banner_title"
#   type = "single_line_text_field"
#   name = "Banner title"
#   description = "Enter a title for the banner"
